### PR TITLE
Add .travis.yml and test target

### PR DESCRIPTION
**Pull request by dmjio**

### CODE REVIEW

**Comment by chessai** [comment]
Why not use haskell-ci (which is really good), using travis for ubuntu? Unless you can have multiple travis setups for nix and non-nix builds. We could potentially test-drive typhon here for nix

File: arrayfire.cabal [hunk 1]
```diff
@@ -90,14 +90,22 @@ library
...
     ld-options:
       -Wl,-rpath /opt/arrayfire/lib
 
+  if os(OSX) && !flag(disable-default-paths)
+    include-dirs:
+      /opt/arrayfire/include
+    extra-lib-dirs:
+      /opt/arrayfire/lib64
+    ld-options:
+      -Wl,-rpath /opt/arrayfire/lib64
```
[the remark this answers is not in the document]
Comment (dmjio) [reply arrayfire.cabal]: I tried both, still no luck. Don't have this issue on OSX, only Ubuntu.

**Comment by dmjio** [comment]
@chessai I'll check out haskell-ci tonight, bigger issue is why cabal on ubuntu doesn't respect `extra-lib-dirs` and `extra-include-dirs` in the cabal file after `cabal configure`

File: arrayfire.cabal (hunk 1 above)
[the remark this answers is not in the document]
Comment (dmjio) [reply arrayfire.cabal]: I bet `nix` modifies my usage of `clang`.

**Comment by noughtmare** [comment]
@chessai try passing the `-v3` flag to cabal.

**Comment by chessai** [comment]
why is a travis build not triggering on the most recent commits?

**Comment by noughtmare** [comment]
```
/usr/bin/gcc returned ExitFailure 1 with error message:
gcc: error: /opt/arrayfire/lib: No such file or directory
```

I think this is because of the `ld-options` field in the cabal file. I think it is best if the entire field is removed completely.

**Comment by chessai** [comment]
okay, configure seems to succeed now. however, hspec-discover fails.

**Comment by noughtmare** [comment]
Yes, I fixed that error on my machine by running `cabal install hspec-discover`.

**Comment by chessai** [comment]
most recent failure seems spurious (just adding hvr-ppa)

**Comment by chessai** [comment]
changed `cabal` to `${CABAL}`. typo

**Comment by chessai** [comment]
use $WITHCOMPILER

**Comment by chessai** [comment]
sorry, i keep forgetting that git with do weird things with '$'-prefixed strings.

**Comment by noughtmare** [comment]
Now we're seeing real errors :tada:

**Comment by chessai** [comment]
okay, the library is building, but running anything is failing with:

```
/tmp/dist-test.N8AS/dist-newstyle/build/x86_64-linux/ghc-8.8.1/arrayfire-0.1.0.0/build/libHSarrayfire-0.1.0.0-inplace.a(LAPACK.o)(.text+0x71f): error: undefined reference to 'af_pinverse'
/tmp/dist-test.N8AS/dist-newstyle/build/x86_64-linux/ghc-8.8.1/arrayfire-0.1.0.0/build/libHSarrayfire-0.1.0.0-inplace.a(Image.o)(.text+0x48a5): error: undefined reference to 'af_iterative_deconv'
/tmp/dist-test.N8AS/dist-newstyle/build/x86_64-linux/ghc-8.8.1/arrayfire-0.1.0.0/build/libHSarrayfire-0.1.0.0-inplace.a(Image.o)(.text+0x4be4): error: undefined reference to 'af_inverse_deconv'
/tmp/dist-test.N8AS/dist-newstyle/build/x86_64-linux/ghc-8.8.1/arrayfire-0.1.0.0/build/libHSarrayfire-0.1.0.0-inplace.a(LAPACK.o)(.text+0x1000): error: undefined reference to 'af_pinverse'
/tmp/dist-test.N8AS/dist-newstyle/build/x86_64-linux/ghc-8.8.1/arrayfire-0.1.0.0/build/libHSarrayfire-0.1.0.0-inplace.a(Signal.o)(.text+0x4aa): error: undefined reference to 'af_approx1_uniform'
/tmp/dist-test.N8AS/dist-newstyle/build/x86_64-linux/ghc-8.8.1/arrayfire-0.1.0.0/build/libHSarrayfire-0.1.0.0-inplace.a(Signal.o)(.text+0xa6f): error: undefined reference to 'af_approx2_uniform'
```

**Comment by noughtmare** [comment]
That was fixed in #17

**Comment by chessai** [comment]
ok, rebasing

**Comment by chessai** [comment]
once a build with 8.8.1 passes, i will re-add the older ghcs

**Comment by noughtmare** [comment]
It seems that #23 forgot to also remove the tests for the Ord instance.

**Comment by chessai** [comment]
```
/tmp/dist-test.Iv7D/dist-newstyle/build/x86_64-linux/ghc-8.8.1/arrayfire-0.3.0.0/t/test/build/test/test: error while loading shared libraries: libaf.so.3: cannot open shared object file: No such file or directory
Test suite test: FAIL 
Test suite logged to: /tmp/dist-test.Iv7D/dist-newstyle/build/x86_64-linux/ghc-8.8.1/arrayfire-0.3.0.0/t/test/test/arrayfire-0.3.0.0-test.log 
0 of 1 test suites (0 of 1 test cases) passed. 
-----BEGIN CABAL OUTPUT-----
cabal: Tests failed for test:test from arrayfire-0.3.0.0.
-----END CABAL OUTPUT-----
```

looks like this isnt getting copied in properly

**Comment by noughtmare** [comment]
It is strange, there are two builds, pr and push, and they give different outputs:

* https://travis-ci.org/arrayfire/arrayfire-haskell/builds/608426254?utm_source=github_status&utm_medium=notification
* https://travis-ci.org/arrayfire/arrayfire-haskell/builds/608426245?utm_source=github_status&utm_medium=notification

**Comment by chessai** [comment]
hmm. that is strange.

**Comment by chessai** [comment]
do i need to remove the Ord tests from the test suite?

**Comment by noughtmare** [comment]
Yes, I think so.

**Comment by chessai** [comment]
now we at least see the same error on both.

**Comment by noughtmare** [comment]
Oh, I think I know how to fix this. The [linux documentation of arrayfire](http://arrayfire.org/docs/installing.htm#Linux) mentions that you have to do this:

> Given sudo permissions, you can add the ArrayFire libraries via ldconfig like so:
> ```
> echo /opt/arrayfire/lib64 > /etc/ld.so.conf.d/arrayfire.conf
>  sudo ldconfig
> ```
> Otherwise, you will need to set the LD_LIBRARY_PATH environment variable in order to let your shared library loader find the ArrayFire libraries.

**Comment by noughtmare** [comment]
I think that is also the reason for the ld-options field in the cabal file.

So another alternative we have is putting:

```
ld-options: -Wl,-rpath /opt/arrayfire/lib64
```
back in the cabal file.

**Comment by chessai** [comment]
we could do that. would it be better instead to do `export LD_LIBRARY_PATH="/opt/arrayfire/lib64:$LD_LIBRARY_PATH"`?

**Comment by noughtmare** [comment]
Yes, that would also work.

**Comment by noughtmare** [comment]
I don't know if it carries over from before-install to script, but we will see.

**Comment by chessai** [comment]
me either. i should probably just do it right after the arrayfire script finishes.

**Comment by chessai** [comment]
failure on push is spurious.

**Comment by chessai** [comment]
actually, those have to be persisting, because a lot of them are actually used during install. so i'm less worried about that. for example, if the extension to PATH to include $CABALHOME/bin didn't persist, the hspec-discover failure would still be occurring.

**Comment by chessai** [comment]
extending LD_LIBRARY_PATH worked.

Test suite now fails with:

```
Failures:
  test/ArrayFire/ArithSpec.hs:31:7: 
  1) ArrayFire.Arith, Arith tests, Should take cubed root
       expected: ArrayFire Array
                 [1 1 1 1]
                     3.0000 
                 
        but got: ArrayFire Array
                 [1 1 1 1]
                     3.0000 
                 
  To rerun use: --match "/ArrayFire.Arith/Arith tests/Should take cubed root/"
Randomized with seed 938744424
```

Which i think is a problem with floating point arithemtic

**Comment by noughtmare** [comment]
> ```
> test/ArrayFire/ArithSpec.hs:31:7: 
> 1) ArrayFire.Arith, Arith tests, Should take cubed root
>      expected: ArrayFire Array
>                [1 1 1 1]
>                    3.0000 
>
>       but got: ArrayFire Array
>                [1 1 1 1]
>                    3.0000 
>```

:thinking:

**Comment by chessai** [comment]
perhaps we should add a `shouldBeEps :: Array Double -> ArrayFire Double -> Expectation` that compares for equality within some epsilon.

File: test/ArrayFire/ArithSpec.hs [hunk 2]
```diff
@@ -22,23 +22,23 @@ spec =
...
            matrix @Int (2,2) [[2,2],[2,2]]
     it "Should take cubed root" $ do
-      3 `shouldBe` cbrt @Double 27
+      3 `shouldBeEps` cbrt @Double 27
     it "Should take square root" $ do
-      2 `shouldBe` sqrt @Double 4
+      2 `shouldBeEps` sqrt @Double 4
     it "Should lt Array" $ do
-      2 `A.lt` (3 :: Array Double) `shouldBe` True
+      2 `A.lt` (3 :: Array Double) `shouldBeEps` True
```
Comment (noughtmare) [inline test/ArrayFire/ArithSpec.hs]: This is not the solution. `lt` returns an array of doubles, and you compare it with a boolean. You could do:

```
      2 `A.lt` (3 :: Array Double) `shouldBe` 1
```

Comment (chessai) [reply test/ArrayFire/ArithSpec.hs]: ah, yeah, that shouldn't have been changed there.

Comment (noughtmare) [reply test/ArrayFire/ArithSpec.hs]: But maybe this should wait until after #24

Comment (noughtmare) [reply test/ArrayFire/ArithSpec.hs]: @chessai read my comment more carefully, it is not just about `shouldBeEps`.

**Comment by chessai** [comment]
push failure is spurious

File: test/ArrayFire/ArithSpec.hs (hunk 2 above)
Comment (chessai) [reply test/ArrayFire/ArithSpec.hs]: yeah, sorry. i'm going to remove these for now.

**Comment by chessai** [comment]
nice. it built.

**Comment by chessai** [comment]
added ghc 8.6.5 and 8.4.4.

**Comment by chessai** [comment]
Configure fails on older ghcs/cabal 2.4. Havent looked into it.

**Comment by chessai** [comment]
i am going to get arrayfire locally so i can test without travis. i don't know why configure is failing on older ghcs, but not 881 with cabal 3.0

**Comment by noughtmare** [comment]
> lapack spec: failing with "free(): invalid next size (normal)" 

I get a similar error message in https://github.com/arrayfire/arrayfire-haskell/issues/13#issuecomment-549938655.

**Comment by chessai** [comment]
just trying to appease travis right now, because locally everything is fine.

**Comment by chessai** [comment]
OK, we now have CI for GHC 8.4.4, 8.6.5, and 8.8.1. @noughtmare @dmjio please review when you have time.

**Comment by chessai** [comment]
have to add back LAPACK/doctest tests

**Comment by dmjio** [comment]
We have a working nix build w/ GitHub CI for linux / osx now, #67 #69
